### PR TITLE
Release v3.0.0

### LINKED ISSUE #644: Update pypi to version 2
Current version on [pypi](https://pypi.python.org/pypi/Flask-Security) is 1.7.5 and miss new functions such as i18n, etc..

It would be nice to be able to install releases from pypi or at least have git tags to use with pip.

### PR DESCRIPTION
**Pull request by jirikuncar**
(closes #644)

### CODE REVIEW

**Comment by avilaton** [comment]
I see that 3.0.0 is released but documentation at https://flask-security.readthedocs.io is still old, any change we get a new docs build?

**Comment by jirikuncar** [comment]
@avilaton I have added `3.0.0` and `develop` builds on readthedocs.

**Comment by avilaton** [comment]
Thanks @jirikuncar, I appreciate that. It is still not clear to me why 3.0.0 isn't the actual latest release.
We were looking at the code to see if it should be the case that a `user.is_active=False` value should actually log the user out or not.

It appears to be that nothing is done with a user account which is deactivated after logging in. We want to actually kick the user out on the next request if the account is deactivated while the user is logged in.

We were reading the code and found https://github.com/mattupstate/flask-security/blob/develop/docs/customizing.rst#authorization-with-oauth2
and found the override to _get_login_manager could be a nice place for that, but it is not that clean cut in 1.7.5 nor in 3.0.0.

Any chance we get what is currently in `develop` to be released as 3.0.1?

**Comment by jirikuncar** [comment]
> Any chance we get what is currently in develop to be released as 3.0.1?

@avilaton I will need to find some time to compile release notes. Any help is appreciated ;) There were some bigger changes and config options which might deserve to bump version to `3.1.0`.

**Comment by avilaton** [comment]
Took a shot at drafting CHANGES from 3.0.0 to current develop, not sure how to prune that list but it should be a complete list of changes. 
https://github.com/mattupstate/flask-security/pull/788

**Pull request merged**
