### PR TITLE
Fixes ActivateUser and DeactivateUser commands

### PR DESCRIPTION
**Pull request by edouardberthe**
Converts user_identifier coming from ActivateUserCommand and DeactivateUserCommand to user entity in datastore.

### CODE REVIEW

**Comment by edouardberthe** [comment]
https://github.com/mattupstate/flask-security/issues/458

**Comment by edouardberthe** [comment]
Hi, could I please have a review on this PR? 
I have added a test to correct the slight decrease in test coverage.
Thx

**Comment by edouardberthe** [comment]
Hi, could I have please a review on this PR ?

Thanks

**Comment by jirikuncar** [comment]
@edouardberthe wouldn't be better to fix it in the `script.py:_ToggleActiveCommand`?

**Comment by jirikuncar** [comment]
New Click command line interface has been implemented in 93ae74b679fec7b58a110611a5f7cfe1ae23a423.

**Pull request closed without merging**
