### PR TITLE
replace token loader with request loader to fix #81

### LINKED ISSUE #81: UnicodeEncodeError when email template contains non-ascii utf8
Running the following test app

``` python
from flask import Flask
from flask_security import Security
from flask_security.datastore import UserDatastore
from flask_security.utils import send_mail

app = Flask(__name__)
security = Security(app, UserDatastore(None, None))

@security.send_mail_task
def send_mail_task(msg):
    msg.as_string()

with app.test_request_context():
    send_mail('subject', 'root@localhost.invalid', 'test')
```

with `./templates/security/email/test.html` and `./templates/security/email/test.txt` files containing non-ascii utf8, e.g. copyright symbol `u'\xa9'`

```
©
```

Results in UnicodeEncodeError:

```
Traceback (most recent call last):
  File "app.py", line 14, in <module>
    send_mail('subject', 'root@localhost.invalid', 'test')
  File "/tmp/virtualenv/lib/python2.6/site-packages/flask_security/utils.py", line 233, in send_mail
    _security._send_mail_task(msg)
  File "app.py", line 11, in send_mail_task
    msg.as_string()
  File "/tmp/virtualenv/lib/python2.6/site-packages/flask_mail.py", line 235, in as_string
    alternative.attach(self._mimetext(self.body, 'plain'))
  File "/tmp/virtualenv/lib/python2.6/site-packages/flask_mail.py", line 217, in _mimetext
    return MIMEText(text, _subtype=subtype, _charset=charset)
  File "/usr/lib/python2.6/email/mime/text.py", line 30, in __init__
    self.set_payload(_text, _charset)
  File "/usr/lib/python2.6/email/message.py", line 224, in set_payload
    self.set_charset(charset)
  File "/usr/lib/python2.6/email/message.py", line 266, in set_charset
    self._payload = charset.body_encode(self._payload)
  File "/usr/lib/python2.6/email/charset.py", line 387, in body_encode
    return email.base64mime.body_encode(s)
  File "/usr/lib/python2.6/email/base64mime.py", line 147, in encode
    enc = b2a_base64(s[i:i + max_unencoded])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 0: ordinal not in range(128)
```

From earlier experience with `render_template` I know it is returning `unicode` which is interchangeable with `str` while you're using only ascii characters, but as soon as you use something else it starts to make a difference and exceptions like this happen.

At some point, I think, that unicode must be explicitly encoded to utf8, but I don't know whether it's Flask-Security job to do, or whether Flask-Mail / email are supposed to accept unicode and deal with appropriately.

Either way as a test adding `.encode('utf-8')` to both `render_template` calls in `utils.py` makes the exception go away. But I don't know if that's the right way to fix this.

### LINKED ISSUE #557: token_loader method of Flask-Login's LoginManager object has been removed
The token_loader method of Flask-Login's LoginManager object has been removed, predictably causing a `AttributeError: 'LoginManager' object has no attribute 'token_loader'` error.

The method is used here: https://github.com/mattupstate/flask-security/blob/9e5865d9735b0b292360f63588ed4725c376757e/flask_security/core.py#L226

The method was removed by @alanhamlett in this commit: https://github.com/maxcountryman/flask-login/commit/f4ff19c33356999e96e3c5b4e80bc7788c85d7a3#diff-ef9a1bd470a8fcf8c774e8f67e4ccc40L205

I'm not sure how to fix this issue so I wanted to share it. I searched the relevant keywords and did not find an existing issue. Please let me know if you have any questions.

Thank you, I've enjoyed using this package.

### PR DESCRIPTION
**Pull request by alanhamlett**
Just moved some code around, but the main change is using `request_loader` on the login manager instead of `token_loader` to fix #557.

### CODE REVIEW

**Comment by jonafato** [comment]
Flask-Security's dependency on Flask-Login is [version-restricted](https://github.com/mattupstate/flask-security/blob/e6cddc63bd070851760136a6247a0542897eb349/requirements.txt#L2). Can you update the versions with this change?

**Comment by datashaman** [comment]
Is something holding this up?

**Comment by alanhamlett** [comment]
> Is something holding this up?

Not that I know of, I think the maintainers forgot to merge it.

**Comment by datashaman** [comment]
For anyone else faced with this, put: `Flask-Login===0.3.2` into your `requirements.txt`, run `pip install -r requirements.txt` and it will automagically do the right thing. :-)

**Comment by jirikuncar** [comment]
@datashaman you can replace `Flask-Security` dependency with `Flask-Security-Fork` which includes this patch (no need to change imports since it's drop-in replacement).

**Comment by datashaman** [comment]
@jirikuncar thanks!

**Comment by chrisutpg** [comment]
Jirikuncar, thanks for the heads up! That saved me!

**Comment by alanhamlett** [comment]
THanks @jirikuncar!

**Pull request merged**
