### PR TITLE
Initial localization support

### PR DESCRIPTION
**Pull request by d1ff**
This PR adds basic localization support with [Flask-BabelEx](https://pythonhosted.org/Flask-BabelEx/). It is based on similar implementation from [Flask-Admin](https://github.com/flask-admin/flask-admin) project.

Also, I've added an example translation to Russian.

### CODE REVIEW

**Comment by pors** [comment]
I think this is brilliant! Would be nice if it could be merged @mattupstate

**Comment by marciorf** [comment]
Does it works?

How can I add a pt_BR translation?

**Comment by andjelx** [comment]
[Corrected patch which successfully applies on 1.7.5](https://gist.github.com/andjelx/357c28412cb390f15d74af1b40a04f61)

**Comment by jirikuncar** [comment]
Merged via #617.

**Pull request closed without merging**
