### PR TITLE
Fix problem with LocalProxy for email_sender

### PR DESCRIPTION
**Pull request by fmerges**
This pull request is to solve the bug #782

### CODE REVIEW

**Comment by avilaton** [comment]
What problem is this solving? Would you please add a failing test that this fixes?

**Comment by fmerges** [comment]
Sorry my bad, I forgot to add the issue this pull is related to.

**Comment by jirikuncar** [comment]
@fmerges can you please rebase your PR on top of `develop` branch?

**Comment by fmerges** [comment]
Just noticed that on the develop branch this problem is already fixed. So the PR for development branch is not needed. See:

https://github.com/mattupstate/flask-security/blob/89198288bc416a7921b4973d8e897993942bb428/flask_security/utils.py#L385-L387

It's just in the current master where it is broken...

**Pull request closed without merging**
