### PR TITLE
Fixes #416 Changing is_authenticated from function to property & updating Flask-…

### LINKED ISSUE #416: is_authenticated() etc. methods break with Flask-Login 0.3.0
Which changes them to properties and causes them to raise `TypeError`s all over the place. 

Relevant Flask-Login changelog: https://github.com/maxcountryman/flask-login/blob/5415c146df9dd560cc9475227c34866851532e9e/test_login.py

### PR DESCRIPTION
**Pull request by ialex**
…Login>=0.3.0

### CODE REVIEW

**Comment by jcwdb** [comment]
Would be nice to merge !

**Comment by rochacbruno** [comment]
I think it is not nice to have ```Flask-Login>=0.3.0``` the best is to fix it, if going to upgrade make this ```Flask-Login==0.3.0``` and do it with all the other requirements. 

This https://github.com/mattupstate/flask-security/pull/419 by @maxcountryman (maintainer of Flask-Login) does that. But it can be fixed now to 0.3.0

You can set requires.io to monitor outdated packages and them, upgrade only if tests are passing, and it is safe.

**Comment by rochacbruno** [comment]
BTW:

```
Flask>=0.9,<0.10.2
Flask-Login==0.3.0
Flask-Mail==0.7.3
Flask-Principal==0.3.3
Flask-WTF==0.8
itsdangerous==0.17
passlib==1.6.1
```

**Comment by ialex** [comment]
Closing in favor of #393

**Comment by fuhrysteve** [comment]
@ialex I disagree- I believe this solution is better than #393 as this solution drops backward compatibility with unsupported versions of `Flask-Login` in the next major release of flask-security.

However, I think the appropriate requirements.txt entry is:

`Flask-Login>=0.3.0,<0.4`

**Comment by fuhrysteve** [comment]
Please see my comment here:

https://github.com/mattupstate/flask-security/pull/393#issuecomment-142644818

I think you had it right!

**Comment by ialex** [comment]
Reopen it, will make the changes later this afternoon

**Comment by blacked** [comment]
when this will be merged?

**Comment by mattupstate** [comment]
Thanks very much, for this!

**Pull request merged**
