### PR TITLE
reset_password: handle JSON requests (#453)

### PR DESCRIPTION
**Pull request by mephi42**
Another stab at #468 and #535.

### CODE REVIEW

**Comment by mephi42** [comment]
@lnielsen Could you please take a look at this PR?

**Review by jwag956 — COMMENTED** [review]
I did something similar in:
https://github.com/jwag956/flask-security which is my fork.

I was solving the issue of a single-page-application which a) uses JSON api and b) needs redirect URls that are in fact API requests (not rendered HTML).
Since reset_password USUALLY comes in as a GET from an email confirmation - I needed to add redirect URLs/APIs.

I found your PR since I am getting my fork to build and hooked up to travis CI etc. And you have fixed a few other issues (thanks)!.

**Comment by mephi42** [comment]
@jwag956 this is my use case as well. Apparently quite a few people needed that in the past too, so I've decided to revive this topic.

@jirikuncar, @lnielsen, Gentle ping.

**Comment by jwag956** [comment]
You can see my changes at: https://github.com/jwag956/flask-security/commits/develop

Also - in an effort to kickstart flask-security and get a release cadence going - I have formalized my fork - it is up on pypi, travis, readthedocs as flask-security-too.

My plan is to pick up obvious/easy already merged PRs from 'develop' branch to get started. Then improving my changes for json/APIs and getting those in.

**Comment by jwag956** [comment]
I have merged my fix to this and confirmation, passwordless login that handle the case you are working on as well as other. In particular, for single-page-applications - the UI needs control on the GET on the reset password link. This will be part of my 3.2.0 release.

please see: https://github.com/jwag956/flask-security/pull/81

I will have this up on pypi as a rc candidate in a day or so.

**Comment by mephi42** [comment]
That sounds really good, thanks! I will give it a try once it's on pypi.

**Comment by jwag956** [comment]
@mephi42 It is now available as 3.2.0rc1 at:
https://pypi.org/project/Flask-Security-Too/#history

**Pull request closed without merging**
